# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS rl::std rl::math rl::util rl::xml rl::kin rl::mdl rl::hal rl::sg rl::plan)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target rl::std
add_library(rl::std INTERFACE IMPORTED)

set_target_properties(rl::std PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
)

# Create imported target rl::math
add_library(rl::math INTERFACE IMPORTED)

set_target_properties(rl::math PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::std;Boost::headers;Eigen3::Eigen"
)

# Create imported target rl::util
add_library(rl::util INTERFACE IMPORTED)

set_target_properties(rl::util PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
)

# Create imported target rl::xml
add_library(rl::xml INTERFACE IMPORTED)

set_target_properties(rl::xml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "Boost::headers;LibXml2::LibXml2;LibXslt::LibXslt"
)

# Create imported target rl::kin
add_library(rl::kin STATIC IMPORTED)

set_target_properties(rl::kin PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::math;rl::std;rl::xml;Boost::headers"
)

# Create imported target rl::mdl
add_library(rl::mdl STATIC IMPORTED)

set_target_properties(rl::mdl PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RL_MDL_NLOPT"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::math;rl::std;rl::xml;Boost::headers;NLopt::nlopt"
)

# Create imported target rl::hal
add_library(rl::hal STATIC IMPORTED)

set_target_properties(rl::hal PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::math;rl::util;Boost::headers;ws2_32"
)

# Create imported target rl::sg
add_library(rl::sg STATIC IMPORTED)

set_target_properties(rl::sg PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RL_SG_BULLET;RL_SG_FCL;RL_SG_ODE;RL_SG_PQP;RL_SG_SOLID"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::math;rl::std;rl::util;rl::xml;Bullet::BulletCollision;Bullet::BulletDynamics;Bullet::BulletSoftBody;Bullet::LinearMath;Coin::Coin;fcl::fcl;ODE::ODE;PQP::PQP;solid3::solid3"
)

# Create imported target rl::plan
add_library(rl::plan STATIC IMPORTED)

set_target_properties(rl::plan PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rl-0.7.0"
  INTERFACE_LINK_LIBRARIES "rl::kin;rl::math;rl::mdl;rl::sg;rl::util;rl::xml;Boost::headers"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/rl-export-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
